apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: jalaaj/backend:4.0
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_HOST
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGO_PORT
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MONGO_USERNAME
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MONGO_PASSWORD
        - name: BACKEND_BIND_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_BIND_HOST
        - name: BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_PORT