apiVersion: v1
kind: Service
metadata:
  name: frontend-{{ include "my-app.fullname" . }}
spec:
  type: {{ .Values.frontendServiceType }}
  ports:
    - port: {{ .Values.frontendPort }}
      targetPort: {{ .Values.frontendPort }}
      nodePort: {{ .Values.frontendServiceNodePort }}
  selector:
    app: frontend-{{ include "my-app.fullname" . }}
