apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-{{ include "my-app.fullname" . }}
  labels:
    app: mongodb-{{ include "my-app.fullname" . }}
spec:
  replicas: {{ .Values.mongodbReplicas }}
  selector:
    matchLabels:
      app: mongodb-{{ include "my-app.fullname" . }}
  template:
    metadata:
      labels:
        app: mongodb-{{ include "my-app.fullname" . }}
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.mongodbImage }}"
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret-{{ include "my-app.fullname" . }}
                key: MONGO_INITDB_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret-{{ include "my-app.fullname" . }}
                key: MONGO_INITDB_ROOT_PASSWORD
        ports:
          - containerPort: {{ .Values.mongodbPort }}
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc-{{ include "my-app.fullname" . }}
