apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: {{ .Values.mongodbStorageSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "{{ .Values.mongodbStorageClass }}"
  hostPath:
    path: /mnt/data/mongo
