apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodbStorageSize }}
  storageClassName: "{{ .Values.mongodbStorageClass }}"
