apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-{{ include "my-app.fullname" . }}
  labels:
    app: backend-{{ include "my-app.fullname" . }}
spec:
  replicas: {{ .Values.backendReplicas }}
  selector:
    matchLabels:
      app: backend-{{ include "my-app.fullname" . }}
  template:
    metadata:
      labels:
        app: backend-{{ include "my-app.fullname" . }}
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backendImage }}"
        ports:
          - containerPort: {{ .Values.backendPort }}
        env:
          - name: MONGO_HOST
            value: "{{ .Values.backendEnvMongoHost }}"
          - name: MONGO_PORT
            value: "{{ .Values.backendEnvMongoPort }}"
          - name: BACKEND_BIND_HOST
            value: "{{ .Values.backendBindHost }}"
          - name: BACKEND_PORT
            value: "{{ .Values.backendPort }}"
