apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backendPort }}
      targetPort: {{ .Values.backendPort }}
  selector:
    app: backend-{{ include "my-app.fullname" . }}
